In [96]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd 
import numpy as np
from matplotlib import pyplot as plt
#from sklearn import datasets
from IPython.display import Image
from sklearn import tree
import pydotplus

r = pd.read_csv('/home/vikas/Downloads/Social_Network_Ads.csv')
r.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [97]:
x1=r.iloc[:,[2,3]].values
y1= r.iloc[:,4].values
#col_name = read[['Age','EstimatedSalary']].columns
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x1,y1,test_size = 0.2,random_state = 10)


from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
x_train = sd.fit_transform(x_train)
x_test= sd.fit_transform(x_test)

from sklearn.tree import DecisionTreeClassifier
dtc1 = DecisionTreeClassifier()
clasifier = dtc1.fit(x_train,y_train)
dtc = DecisionTreeClassifier()
dtc.fit(x1,y1)
y_pred = dtc1.predict(x_test)
y_pred


from sklearn import metrics
print('Acuracy',metrics.accuracy_score(y_pred,y_test))

Acuracy 0.9


/home/vikas/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


# DecisionTreeClassifier

In [72]:
from sklearn import tree

In [73]:
x= [[0,0],[1,1]]
y = [0,1]
dtc = tree.DecisionTreeClassifier()
dtc.fit(x,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [74]:
dtc.predict([[2,2]])

array([1])

In [75]:
dtc.predict_proba([[7,6]])

array([[ 0.,  1.]])

In [76]:
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn import datasets
read = datasets.load_iris()
x= read.data
y =read.target
dtc = DecisionTreeClassifier()
dtc1 = dtc.fit(x,y)

In [77]:
# tree.plot_tree(dtc1.fit(read.data,read.target))

In [78]:

# import datasets 
# dataset = pd.read_csv('Data.csv')  
# #alternatively open up .csv file to read data 
  
dataset = np.array( 
[['Asset Flip', 100, 1000], 
['Text Based', 500, 3000], 
['Visual Novel', 1500, 5000], 
['2D Pixel Art', 3500, 8000], 
['2D Vector Art', 5000, 6500], 
['Strategy', 6000, 7000], 
['First Person Shooter', 8000, 15000], 
['Simulator', 9500, 20000], 
['Racing', 12000, 21000], 
['RPG', 14000, 25000], 
['Sandbox', 15500, 27000], 
['Open-World', 16500, 30000], 
['MMOFPS', 25000, 52000], 
['MMORPG', 30000, 80000] ]) 
print(dataset)

[['Asset Flip' '100' '1000']
 ['Text Based' '500' '3000']
 ['Visual Novel' '1500' '5000']
 ['2D Pixel Art' '3500' '8000']
 ['2D Vector Art' '5000' '6500']
 ['Strategy' '6000' '7000']
 ['First Person Shooter' '8000' '15000']
 ['Simulator' '9500' '20000']
 ['Racing' '12000' '21000']
 ['RPG' '14000' '25000']
 ['Sandbox' '15500' '27000']
 ['Open-World' '16500' '30000']
 ['MMOFPS' '25000' '52000']
 ['MMORPG' '30000' '80000']]


In [79]:
x11 = dataset[:, 1:2].astype(int)
x11

array([[  100],
       [  500],
       [ 1500],
       [ 3500],
       [ 5000],
       [ 6000],
       [ 8000],
       [ 9500],
       [12000],
       [14000],
       [15500],
       [16500],
       [25000],
       [30000]])

In [80]:
y11 = dataset[:, 2].astype(int)  
y11

array([ 1000,  3000,  5000,  8000,  6500,  7000, 15000, 20000, 21000,
       25000, 27000, 30000, 52000, 80000])

In [82]:
from sklearn.tree import DecisionTreeRegressor  
  
 
regressor = DecisionTreeRegressor(random_state = 0)  
  
regressor.fit(x11, y11) 

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [89]:
#predicting a new value 
# test the output by changing values, like 3750 
y_pred = regressor.predict(2222) 
y_pred

array([ 5000.])

In [95]:
# from sklearn.tree import export_graphviz  
  
# # export the decision tree to a tree.dot file 
# # for visualizing the plot easily anywhere 
# plt = export_graphviz(regressor, out_file ='tree.dot', 
#                feature_names =['Production Cost'])  
# plt.show()

In [94]:

X_grid = np.arange(min(X), max(X), 0.01) 
  
# reshape for reshaping the data into  
# a len(X_grid)*1 array, i.e. to make 
# a column out of the X_grid values 
X_grid = X_grid.reshape((len(X_grid), 1))  
  
# scatter plot for original data 
plt.scatter(x11, y11, color = 'red') 
  
# plot predicted data 
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')  
  
# specify title 
plt.title('Profit to Production Cost (Decision Tree Regression)')  
  
# specify X axis label 
plt.xlabel('Production Cost') 
  
# specify Y axis label 
plt.ylabel('Profit') 
  
# show the plot 
plt.show() 

AttributeError: 'NoneType' object has no attribute 'scatter'

In [92]:
# dot_tree = tree.export_graphviz(regressor,out_file='dot.tree', 
#                                 feature_names =['Production Cost'])


In [93]:
# graph = pydotplus.graph_from_dot_data(dot_tree)

In [14]:
import pandas as pd
#from category_encoders import BinaryEncoders

import category_encoders as a
data = pd. DataFrame({'class':['g','b','a','b','d','e','d','f',
                               'g','h','h','k','h','i','s','p','z']})
print(data)
v = a.BinaryEncoder(cols= ['class'])
v.fit_transform(data)

   class
0      g
1      b
2      a
3      b
4      d
5      e
6      d
7      f
8      g
9      h
10     h
11     k
12     h
13     i
14     s
15     p
16     z


class_0  class_1  class_2  class_3  class_4
0         0        0        0        0        1
1         0        0        0        1        0
2         0        0        0        1        1
3         0        0        0        1        0
4         0        0        1        0        0
5         0        0        1        0        1
6         0        0        1        0        0
7         0        0        1        1        0
8         0        0        0        0        1
9         0        0        1        1        1
10        0        0        1        1        1
11        0        1        0        0        0
12        0        0        1        1        1
13        0        1        0        0        1
14        0        1        0        1        0
15        0        1        0        1        1
16        0        1        1        0        0