# Vectorization

In [1]:
train_set = ("The sky is blue.", "The sun is bright.")
test_set = ("The sun in the sky is bright.",
            "We can see the shining sun, the bright sun.")

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()


In [3]:
cv.fit(train_set)
cv.vocabulary_


{'blue': 0, 'bright': 1, 'is': 2, 'sky': 3, 'sun': 4, 'the': 5}

In [4]:
print(test_set)

('The sun in the sky is bright.', 'We can see the shining sun, the bright sun.')


In [5]:
xy = cv.transform(test_set)
print(xy)
xy.toarray()

  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	2
  (1, 1)	1
  (1, 4)	2
  (1, 5)	2


array([[0, 1, 1, 1, 1, 2],
       [0, 1, 0, 0, 2, 2]])

In [6]:
cv.transform(['hi ths is vikas having blue ball and red sun in the sky']).toarray()

array([[1, 0, 1, 1, 1, 1]])

In [7]:
cv.inverse_transform(xy)

[array(['bright', 'is', 'sky', 'sun', 'the'],
       dtype='<U6'), array(['bright', 'sun', 'the'],
       dtype='<U6')]

In [8]:
train_set = ("The sky is blue.", "The sun is bright.")
test_set = ("The sun in the sky is bright.",
"We can see the shining sun, the bright sun.")


In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(train_set)
vectorizer.vocabulary_

{'blue': 0, 'bright': 1, 'is': 2, 'sky': 3, 'sun': 4, 'the': 5}

In [15]:
vectorizer.transform(test_set).toarray()

array([[ 0.        ,  0.42519636,  0.30253071,  0.42519636,  0.42519636,
         0.60506143],
       [ 0.        ,  0.37729199,  0.        ,  0.        ,  0.75458397,
         0.53689271]])

# Naive Bayes Algorithem

In [16]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']


# Label Encoding

In [17]:
from sklearn import preprocessing
label_enc = preprocessing.LabelEncoder()
weathe = label_enc.fit_transform(weather)
weathe


array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

# Now combining  these two featurs which will hepl for prediction

In [18]:
temp= label_enc.fit_transform(temp)

temp

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [19]:
Label = label_enc.fit_transform(play)
Label


array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [20]:
featurs = list(zip(weathe,temp))
featurs

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [21]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
#model.fit(weathe,temp)
model.fit(featurs,Label)
print('>>',model.predict([[1,2]]))

>> [1]


# Naive Bayes with Multiple Labels
>[Advanced Lavel] https://www.datacamp.com/community/tutorials/naive-bayes-scikit-learn


> [Youtube video]  1.https://www.youtube.com/watch?v=iGZpJZhqEME  2. https://www.youtube.com/watch?v=Ybs0nEQARsU


https://books.google.co.in/books/about/Neural_Network_Methods_in_Natural_Langua.html?id=8wklDwAAQBAJ&printsec=frontcover&source=kp_read_button&redir_esc=y#v=onepage&q&f=false

# Here you can build a model to classify the type of wine.(Class0,Class1,Class2)

In [22]:
from sklearn import datasets
wine  =  datasets.load_wine()
wine

{'DESCR': 'Wine Data Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- 1) Alcohol\n \t\t- 2) Malic acid\n \t\t- 3) Ash\n\t\t- 4) Alcalinity of ash  \n \t\t- 5) Magnesium\n\t\t- 6) Total phenols\n \t\t- 7) Flavanoids\n \t\t- 8) Nonflavanoid phenols\n \t\t- 9) Proanthocyanins\n\t\t- 10)Color intensity\n \t\t- 11)Hue\n \t\t- 12)OD280/OD315 of diluted wines\n \t\t- 13)Proline\n        \t- class:\n                - class_0\n                - class_1\n                - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80   

In [23]:
wine.feature_names #wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [24]:
wine.target_names

array(['class_0', 'class_1', 'class_2'],
      dtype='<U7')

In [25]:
wine.shape

AttributeError: shape

In [26]:
wine.data.shape

(178, 13)

converting raw data to understandable data 

In [27]:
import pandas as pd 
wine1 = pd.DataFrame(wine.data)
wine1.head()

0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

       12  
0  1065.0  
1  1050.0  
2  1185.0  
3  1480.0  
4   735.0

In [28]:
import pandas as pd 
wine1 = pd.DataFrame(wine.data,columns = wine.feature_names)
wine1.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [29]:
wine.data[0:5]

array([[  1.42300000e+01,   1.71000000e+00,   2.43000000e+00,
          1.56000000e+01,   1.27000000e+02,   2.80000000e+00,
          3.06000000e+00,   2.80000000e-01,   2.29000000e+00,
          5.64000000e+00,   1.04000000e+00,   3.92000000e+00,
          1.06500000e+03],
       [  1.32000000e+01,   1.78000000e+00,   2.14000000e+00,
          1.12000000e+01,   1.00000000e+02,   2.65000000e+00,
          2.76000000e+00,   2.60000000e-01,   1.28000000e+00,
          4.38000000e+00,   1.05000000e+00,   3.40000000e+00,
          1.05000000e+03],
       [  1.31600000e+01,   2.36000000e+00,   2.67000000e+00,
          1.86000000e+01,   1.01000000e+02,   2.80000000e+00,
          3.24000000e+00,   3.00000000e-01,   2.81000000e+00,
          5.68000000e+00,   1.03000000e+00,   3.17000000e+00,
          1.18500000e+03],
       [  1.43700000e+01,   1.95000000e+00,   2.50000000e+00,
          1.68000000e+01,   1.13000000e+02,   3.85000000e+00,
          3.49000000e+00,   2.40000000e-01,   2.180

In [30]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Spliting of dataset in Train test formate fro shake of understanding

In [31]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test = train_test_split(wine.data,wine.target,test_size = 0.2,random_state = 100)

/home/vikas/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [32]:
from sklearn.naive_bayes import  GaussianNB

In [33]:
gnb = GaussianNB()
gnb.fit(x_train,y_train)
y_pred  = gnb.predict(x_test)

In [34]:
from sklearn import metrics
print('Accuracy',metrics.accuracy_score(y_pred,y_test))

Accuracy 1.0
