# numpy Basics

In [118]:
import numpy as np

# 1D arraay

In [119]:
list =[1,2,3,4,5,6,7]
b=np.array(list)

In [120]:
b

array([1, 2, 3, 4, 5, 6, 7])

In [121]:
b+2

array([3, 4, 5, 6, 7, 8, 9])

# 2D array

In [122]:
list = [[1,2,3,4,5],[1,2,3,4,5]]

In [123]:
b =np.array(list)

In [124]:
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [125]:
b =np.array(list,dtype = str) ## dtype int ,float... bool.. object.... 

In [126]:
b

array([['1', '2', '3', '4', '5'],
       ['1', '2', '3', '4', '5']],
      dtype='<U1')

In [127]:
b.astype(int)  #this way u can do

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

Convert to int then to str datatype

In [128]:
b.astype(int).astype(str) ### conversion can anythig that u want

array([['1', '2', '3', '4', '5'],
       ['1', '2', '3', '4', '5']],
      dtype='<U21')

In [129]:
lst =[1,2,3,4,5,0] 
lst1 = np.array(lst, dtype= bool)

In [130]:
lst1

array([ True,  True,  True,  True,  True, False], dtype=bool)

In [131]:
lst = ['a','b',1,2,3,4,'e']
np.array(lst,dtype = str)

array(['a', 'b', '1', '2', '3', '4', 'e'],
      dtype='<U1')

In [132]:
lst1 = np.array(lst,dtype = object) ######objectttttttttttttttt

In [133]:
lst1

array(['a', 'b', 1, 2, 3, 4, 'e'], dtype=object)

In [134]:
type(lst1)

numpy.ndarray

In [135]:
type(lst)

list

Convert an array back to a list

In [136]:
v =lst1.tolist()
v

['a', 'b', 1, 2, 3, 4, 'e']

In [137]:
type(v)

list

In [138]:
lst1.shape

(7,)

In [139]:
lst1

array(['a', 'b', 1, 2, 3, 4, 'e'], dtype=object)

In [140]:
lst1.astype(bool)

array([ True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [141]:
lst1.size

7

In [142]:
lst1.ndim

1

In [143]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [144]:
mat = np.random.randint(1,30,30).reshape(5,6)

In [145]:
mat

array([[ 1, 29, 19, 15, 29, 12],
       [24,  2, 25, 22, 19,  5],
       [ 1,  1, 12,  4,  8, 20],
       [13,  1, 11,  3, 17, 27],
       [26, 26,  8, 29,  5, 17]])

In [146]:
mat[1:3,1:4]

array([[ 2, 25, 22],
       [ 1, 12,  4]])

In [147]:
mat[2,2]

12

In [148]:
mat[4,5]

17

In [149]:
mat[2:4,3:5]#mat[3:,3:]

array([[ 4,  8],
       [ 3, 17]])

In [150]:
mat[0:3:2,0:] #row 1 skip

array([[ 1, 29, 19, 15, 29, 12],
       [ 1,  1, 12,  4,  8, 20]])

In [151]:
mat[0:4:2,0:] ## row 0,2

array([[ 1, 29, 19, 15, 29, 12],
       [ 1,  1, 12,  4,  8, 20]])

In [152]:
mat[1:4:2,0:] #start,stop, step

array([[24,  2, 25, 22, 19,  5],
       [13,  1, 11,  3, 17, 27]])

In [153]:
greater_10  = mat>10
greater_10

array([[False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True, False],
       [False, False,  True, False, False,  True],
       [ True, False,  True, False,  True,  True],
       [ True,  True, False,  True, False,  True]], dtype=bool)

In [154]:
mat[greater_10]

array([29, 19, 15, 29, 12, 24, 25, 22, 19, 12, 20, 13, 11, 17, 27, 26, 26,
       29, 17])

In [155]:
mat

array([[ 1, 29, 19, 15, 29, 12],
       [24,  2, 25, 22, 19,  5],
       [ 1,  1, 12,  4,  8, 20],
       [13,  1, 11,  3, 17, 27],
       [26, 26,  8, 29,  5, 17]])

In [156]:
mat[:-1]

array([[ 1, 29, 19, 15, 29, 12],
       [24,  2, 25, 22, 19,  5],
       [ 1,  1, 12,  4,  8, 20],
       [13,  1, 11,  3, 17, 27]])

In [157]:
mat[:-2]

array([[ 1, 29, 19, 15, 29, 12],
       [24,  2, 25, 22, 19,  5],
       [ 1,  1, 12,  4,  8, 20]])

In [158]:
mat[:-3]

array([[ 1, 29, 19, 15, 29, 12],
       [24,  2, 25, 22, 19,  5]])

In [159]:
mat[:-4]

array([[ 1, 29, 19, 15, 29, 12]])

In [160]:
mat[0]

array([ 1, 29, 19, 15, 29, 12])

In [161]:
mat[0:2]

array([[ 1, 29, 19, 15, 29, 12],
       [24,  2, 25, 22, 19,  5]])

In [162]:
mat[0::2] #step is 2

array([[ 1, 29, 19, 15, 29, 12],
       [ 1,  1, 12,  4,  8, 20],
       [26, 26,  8, 29,  5, 17]])

In [163]:
mat[0:3]

array([[ 1, 29, 19, 15, 29, 12],
       [24,  2, 25, 22, 19,  5],
       [ 1,  1, 12,  4,  8, 20]])

In [164]:
mat[0::3]

array([[ 1, 29, 19, 15, 29, 12],
       [13,  1, 11,  3, 17, 27]])

# How to reverse the rows and  col of the whole array?

 ## reverse the rows

In [165]:
mat

array([[ 1, 29, 19, 15, 29, 12],
       [24,  2, 25, 22, 19,  5],
       [ 1,  1, 12,  4,  8, 20],
       [13,  1, 11,  3, 17, 27],
       [26, 26,  8, 29,  5, 17]])

In [166]:
mat[::-1]

array([[26, 26,  8, 29,  5, 17],
       [13,  1, 11,  3, 17, 27],
       [ 1,  1, 12,  4,  8, 20],
       [24,  2, 25, 22, 19,  5],
       [ 1, 29, 19, 15, 29, 12]])

# reverse the col and row

In [167]:
mat[::-1,::-1]

array([[17,  5, 29,  8, 26, 26],
       [27, 17,  3, 11,  1, 13],
       [20,  8,  4, 12,  1,  1],
       [ 5, 19, 22, 25,  2, 24],
       [12, 29, 15, 19, 29,  1]])

# replace present val with NAN

In [170]:
mat[2,2]=np.nan

ValueError: cannot convert float NaN to integer

In [171]:
mat1 = mat.astype(float)

In [172]:
mat1

array([[  1.,  29.,  19.,  15.,  29.,  12.],
       [ 24.,   2.,  25.,  22.,  19.,   5.],
       [  1.,   1.,  12.,   4.,   8.,  20.],
       [ 13.,   1.,  11.,   3.,  17.,  27.],
       [ 26.,  26.,   8.,  29.,   5.,  17.]])

In [173]:
type(mat1)

numpy.ndarray

In [174]:
mat1[1,1] = np.nan #### not a number

In [175]:
mat1

array([[  1.,  29.,  19.,  15.,  29.,  12.],
       [ 24.,  nan,  25.,  22.,  19.,   5.],
       [  1.,   1.,  12.,   4.,   8.,  20.],
       [ 13.,   1.,  11.,   3.,  17.,  27.],
       [ 26.,  26.,   8.,  29.,   5.,  17.]])

In [176]:
mat1[3,3] = np.inf  ### infinitee

In [177]:
mat1

array([[  1.,  29.,  19.,  15.,  29.,  12.],
       [ 24.,  nan,  25.,  22.,  19.,   5.],
       [  1.,   1.,  12.,   4.,   8.,  20.],
       [ 13.,   1.,  11.,  inf,  17.,  27.],
       [ 26.,  26.,   8.,  29.,   5.,  17.]])

# missing value replace with valuess

In [178]:
miss_val = np.isnan(mat1)|np.isinf(mat1)

In [179]:
#mat1[miss_val] = 1

In [180]:
mat1

array([[  1.,  29.,  19.,  15.,  29.,  12.],
       [ 24.,  nan,  25.,  22.,  19.,   5.],
       [  1.,   1.,  12.,   4.,   8.,  20.],
       [ 13.,   1.,  11.,  inf,  17.,  27.],
       [ 26.,  26.,   8.,  29.,   5.,  17.]])

In [184]:
np.isnan(mat1)

array([[False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], dtype=bool)

In [185]:
np.isinf(mat1)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False]], dtype=bool)

# mean max min std cumulative sum

In [186]:
np.mean(mat1)## whole  mat 

nan

In [187]:
bar = np.min(mat1,axis = 0)  ## column wise
bar

array([  1.,  nan,   8.,   4.,   5.,   5.])

In [188]:
np.min(mat1,axis = 1) ######     row wise

array([  1.,  nan,   1.,   1.,   5.])

In [193]:
np.min(mat1)

nan

In [194]:
np.max(mat1)

nan

In [195]:
np.std(mat1)

nan

In [196]:
np.median(mat1)

/home/vikas/anaconda/lib/python3.6/site-packages/numpy/lib/function_base.py:4016: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)


nan

In [197]:
np.cumsum(mat1) ############   Cumulative Sum

array([   1.,   30.,   49.,   64.,   93.,  105.,  129.,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
         nan,   nan,   nan])

# How to create a new array from an existing array?

In [198]:
mat1

array([[  1.,  29.,  19.,  15.,  29.,  12.],
       [ 24.,  nan,  25.,  22.,  19.,   5.],
       [  1.,   1.,  12.,   4.,   8.,  20.],
       [ 13.,   1.,  11.,  inf,  17.,  27.],
       [ 26.,  26.,   8.,  29.,   5.,  17.]])

In [199]:
mat11 = mat1.copy() # bcz we dont want to change r original matrix we ned .copy() method

In [200]:
mat11

array([[  1.,  29.,  19.,  15.,  29.,  12.],
       [ 24.,  nan,  25.,  22.,  19.,   5.],
       [  1.,   1.,  12.,   4.,   8.,  20.],
       [ 13.,   1.,  11.,  inf,  17.,  27.],
       [ 26.,  26.,   8.,  29.,   5.,  17.]])

In [201]:
 mt =mat11[:3,:3] ## new array from copy() array 

In [202]:
mt

array([[  1.,  29.,  19.],
       [ 24.,  nan,  25.],
       [  1.,   1.,  12.]])

In [203]:
mt[1,1] = 100 ## it will change only in mat11 but  not in mat1

In [204]:
mt

array([[   1.,   29.,   19.],
       [  24.,  100.,   25.],
       [   1.,    1.,   12.]])

In [205]:
mat11

array([[   1.,   29.,   19.,   15.,   29.,   12.],
       [  24.,  100.,   25.,   22.,   19.,    5.],
       [   1.,    1.,   12.,    4.,    8.,   20.],
       [  13.,    1.,   11.,   inf,   17.,   27.],
       [  26.,   26.,    8.,   29.,    5.,   17.]])

In [208]:
mt1 = mat11[0:3,1:3] ## another new mat from the old mat

In [209]:
mt1

array([[  29.,   19.],
       [ 100.,   25.],
       [   1.,   12.]])

In [210]:
mat11 ## here is the copy matrix wiil reflect the changes but  not original mat 

array([[   1.,   29.,   19.,   15.,   29.,   12.],
       [  24.,  100.,   25.,   22.,   19.,    5.],
       [   1.,    1.,   12.,    4.,    8.,   20.],
       [  13.,    1.,   11.,   inf,   17.,   27.],
       [  26.,   26.,    8.,   29.,    5.,   17.]])

In [211]:
mat1

array([[  1.,  29.,  19.,  15.,  29.,  12.],
       [ 24.,  nan,  25.,  22.,  19.,   5.],
       [  1.,   1.,  12.,   4.,   8.,  20.],
       [ 13.,   1.,  11.,  inf,  17.,  27.],
       [ 26.,  26.,   8.,  29.,   5.,  17.]])

# Reshaping and Flattening Multidimensional arrays

In [212]:
mat11

array([[   1.,   29.,   19.,   15.,   29.,   12.],
       [  24.,  100.,   25.,   22.,   19.,    5.],
       [   1.,    1.,   12.,    4.,    8.,   20.],
       [  13.,    1.,   11.,   inf,   17.,   27.],
       [  26.,   26.,    8.,   29.,    5.,   17.]])

In [215]:
mat.reshape(5,5) ## errorrrrrrrrrrrrrr

ValueError: cannot reshape array of size 30 into shape (5,5)

In [216]:
mat11.reshape(6,5)  #mat.reshape(15,2) orrrrrrrrrrrrr mat11.reshape(5,6)

array([[   1.,   29.,   19.,   15.,   29.],
       [  12.,   24.,  100.,   25.,   22.],
       [  19.,    5.,    1.,    1.,   12.],
       [   4.,    8.,   20.,   13.,    1.],
       [  11.,   inf,   17.,   27.,   26.],
       [  26.,    8.,   29.,    5.,   17.]])

# What is the difference between flatten() and ravel()?

# Flatten

In [217]:
mat11

array([[   1.,   29.,   19.,   15.,   29.,   12.],
       [  24.,  100.,   25.,   22.,   19.,    5.],
       [   1.,    1.,   12.,    4.,    8.,   20.],
       [  13.,    1.,   11.,   inf,   17.,   27.],
       [  26.,   26.,    8.,   29.,    5.,   17.]])

In [218]:
mat11.flatten() ## mult dim to single dim

array([   1.,   29.,   19.,   15.,   29.,   12.,   24.,  100.,   25.,
         22.,   19.,    5.,    1.,    1.,   12.,    4.,    8.,   20.,
         13.,    1.,   11.,   inf,   17.,   27.,   26.,   26.,    8.,
         29.,    5.,   17.])

In [221]:
mtt = mat11.flatten()
mtt

array([   1.,   29.,   19.,   15.,   29.,   12.,   24.,  100.,   25.,
         22.,   19.,    5.,    1.,    1.,   12.,    4.,    8.,   20.,
         13.,    1.,   11.,   inf,   17.,   27.,   26.,   26.,    8.,
         29.,    5.,   17.])

In [222]:
mtt[0]= 100 ## doe'nt change th vlaue of the original value
mtt

array([ 100.,   29.,   19.,   15.,   29.,   12.,   24.,  100.,   25.,
         22.,   19.,    5.,    1.,    1.,   12.,    4.,    8.,   20.,
         13.,    1.,   11.,   inf,   17.,   27.,   26.,   26.,    8.,
         29.,    5.,   17.])

In [223]:
mat11  # same as roginal not any val change

array([[   1.,   29.,   19.,   15.,   29.,   12.],
       [  24.,  100.,   25.,   22.,   19.,    5.],
       [   1.,    1.,   12.,    4.,    8.,   20.],
       [  13.,    1.,   11.,   inf,   17.,   27.],
       [  26.,   26.,    8.,   29.,    5.,   17.]])

# Ravel()

In [224]:
mat11

array([[   1.,   29.,   19.,   15.,   29.,   12.],
       [  24.,  100.,   25.,   22.,   19.,    5.],
       [   1.,    1.,   12.,    4.,    8.,   20.],
       [  13.,    1.,   11.,   inf,   17.,   27.],
       [  26.,   26.,    8.,   29.,    5.,   17.]])

In [225]:
matrix = mat11.ravel()

In [226]:
matrix

array([   1.,   29.,   19.,   15.,   29.,   12.,   24.,  100.,   25.,
         22.,   19.,    5.,    1.,    1.,   12.,    4.,    8.,   20.,
         13.,    1.,   11.,   inf,   17.,   27.,   26.,   26.,    8.,
         29.,    5.,   17.])

In [227]:
matrix[1] =222 ##i am changing the value of the position of the index 1 = 100 of the ravel matrix
matrix

array([   1.,  222.,   19.,   15.,   29.,   12.,   24.,  100.,   25.,
         22.,   19.,    5.,    1.,    1.,   12.,    4.,    8.,   20.,
         13.,    1.,   11.,   inf,   17.,   27.,   26.,   26.,    8.,
         29.,    5.,   17.])

In [228]:
## it will change in the matrix but it also affect the original value beloww cell 
#this is the difference between flatten and ravel
mat11

array([[   1.,  222.,   19.,   15.,   29.,   12.],
       [  24.,  100.,   25.,   22.,   19.,    5.],
       [   1.,    1.,   12.,    4.,    8.,   20.],
       [  13.,    1.,   11.,   inf,   17.,   27.],
       [  26.,   26.,    8.,   29.,    5.,   17.]])

# How to create sequences, repetitions and random numbers using numpy?

In [247]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [248]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [249]:
np.arange(0,20,2) ## step size 1...................infinite ( Remember one thing is depends on range u given)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [250]:
np.arange(0,19,-1)

array([], dtype=int64)

In [251]:
np.arange(20,0,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [252]:
np.arange(19,0,-3) #####-1,-2,-2,-3,..............................

array([19, 16, 13, 10,  7,  4,  1])

# Linspace

In [268]:
np.linspace(0,100,10)

array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
         44.44444444,   55.55555556,   66.66666667,   77.77777778,
         88.88888889,  100.        ])

In [269]:
np.linspace(0,100,10,dtype= int)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [270]:
np.linspace(1,100,10)

array([   1.,   12.,   23.,   34.,   45.,   56.,   67.,   78.,   89.,  100.])

In [267]:
np.linspace(1,100,10 , dtype = int)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

# logspace

In [262]:
np.logspace(1,100,15 ,base = 5)

array([  5.00000000e+00,   4.38214217e+05,   3.84063400e+10,
         3.36604085e+15,   2.95009391e+20,   2.58554619e+25,
         2.26604620e+30,   1.98602732e+35,   1.74061082e+40,
         1.52552081e+45,   1.33700982e+50,   1.17179342e+55,
         1.02699307e+60,   9.00085933e+64,   7.88860905e+69])

In [263]:
np.logspace(1,100,15 ,base = 10)

array([  1.00000000e+001,   1.17876863e+008,   1.38949549e+015,
         1.63789371e+022,   1.93069773e+029,   2.27584593e+036,
         2.68269580e+043,   3.16227766e+050,   3.72759372e+057,
         4.39397056e+064,   5.17947468e+071,   6.10540230e+078,
         7.19685673e+085,   8.48342898e+092,   1.00000000e+100])

In [ ]:
np.logspace(1,100,15 ) ######## if u r not given the base size then it will defualt take base as 10 <<<---Remember

In [ ]:
np.zeros([3,3])

In [ ]:
np.ones([5,5])

In [ ]:
np.identity(5)

# How to create repeating sequences?

In [ ]:
var = np.arange(10)

In [ ]:
var

# .repeate()  Times u wanna repeat  the list or array

In [ ]:
b

In [ ]:
np.repeat(var,2)

In [ ]:
np.repeat(var,3) ########1,2,3,4,5............,,,,,,,,,,,,,,

# .tile()

In [ ]:
np.tile(var,2)

# How to generate random numbers?

In [ ]:
value = np.random.randint(0,100)

In [ ]:
value

In [ ]:
np.random.randint((2,2))

In [ ]:
np.random.rand(3,3) ## values between 0 and 1

In [ ]:
np.random.randint(0,10,size =(2,2))

In [ ]:
np.random.randint(0,10,size =(4,5)) ####any size

In [ ]:
np.random.randint(0,12,size = (11,12)) #### any size

In [ ]:
np.random.randint(1,12,size = [3,3])

In [ ]:
np.random.randint(size[2,2]) ########## error bcz = to sign

In [ ]:
np.random.random(size=[2,2])

# Pick 10 items from a given list, with equal probability

In [ ]:
list = ['a','r','t','g','f','4','d','l']

In [ ]:
np.random.randint(list,size=10)

In [ ]:
np.random.choice(list,size=10)

In [ ]:
a=np.random.choice(list,size=10)

In [ ]:
a

In [ ]:
np.count_nonzero(a)

#Pick 10 items from a given list with a predefined probability 'p#  Pick 10 items from a given list with a predefined probability 'p

In [ ]:
np.random.choice(list,size = 10)

# RandomState

In [ ]:
vr  = np.random.RandomState(100)

In [ ]:
vr.rand(3,3) ####### every time it will generate diffenrent values

In [ ]:
vr.rand(3,3)

In [ ]:
vr.rand(3,3)

# seed

In [ ]:
np.random.seed(100)

In [ ]:
vr.rand(3,3)

In [ ]:
vr.rand(3,3)

In [ ]:
vr.rand(3,3)

#How to get the unique items and the counts?

In [ ]:
 bar = np.random.randint(0,10 ,size =6,dtype = int) ########3size(2,3)

In [ ]:
 unique,counts = np.unique(bar, return_counts = True)

In [ ]:
unique

In [ ]:
counts