In [1]:
import numpy as np

In [3]:
np.__version__

'1.13.3'

# How to create a 1D array?

In [9]:
var = np.arange(0,10)

In [10]:
var

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# How to create a boolean array?

In [14]:
np.arange((0,10),size = (3,3),dtype= 'bool')

ValueError: high is out of bounds for bool

In [16]:
np.ones((3,3),dtype = bool) ##### np.full((3,3),True,dtype =bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

# How to extract items that satisfy a given condition from 1D array?
 Extract all odd numbers from arr

In [17]:
varr = np.arange(10)

In [18]:
varr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
varr[0::3]

array([0, 3, 6, 9])

# or

In [20]:
varr[varr%2==1]

array([1, 3, 5, 7, 9])

# How to replace items that satisfy a condition with another value in numpy array?
Replace all odd numbers in arr with -1 without changing arr

In [29]:
N = np.arange(10)

In [30]:
N

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
N[N%2==1]=-1

In [32]:
N

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# OR

In [35]:
A =np.arange(10)
np.where(A%2!=0,-1,N)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# How to reshape an array?

In [37]:
v = np.arange(10)

In [38]:
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
v.reshape(5,2) #(2,5)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# How to stack two arrays horizontally and Veritically

# Vertically

In [51]:
a= np.arange(10)
b= np.arange(10,20)

In [52]:
a,b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [53]:
np.vstack([a,b])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [55]:
np.concatenate([a,b])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# or

In [86]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(0,10).reshape(2,-1)
np.vstack([a,b])
np.r_[a,b]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Horizontally

In [87]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [89]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 0, 0, 0, 0, 0],
       [5, 6, 7, 8, 9, 0, 0, 0, 0, 0]])

In [91]:
np.concatenate([a,b],axis = 1)

array([[0, 1, 2, 3, 4, 0, 0, 0, 0, 0],
       [5, 6, 7, 8, 9, 0, 0, 0, 0, 0]])

# How to generate custom sequences in numpy without hardcoding?
Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
#a = np.array([1,2,3])
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [92]:
a = np.array([1,2,3])

In [93]:
a

array([1, 2, 3])

In [100]:
x = np.repeat(a,3)

In [101]:
y =np.tile(a,3)

In [102]:
np.concatenate([x,y],axis = 0) ############ orrrrrrrrrrrrrrrrrr

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [103]:
np.r_[x,y] #################      or

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [110]:
np.vstack([x,y]) ################ done

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

# How to get the common items between two python numpy arrays?
Get the common items between a and b

In [113]:
a =np.array([1,2,3,4,5,34,7,8])
a

array([ 1,  2,  3,  4,  5, 34,  7,  8])

In [118]:
b  = np.array([1,4,3,5,4,43,7,2])
b

array([ 1,  4,  3,  5,  4, 43,  7,  2])

In [117]:
np.intersect1d(a,b) #intersect1d

array([1, 2, 3, 4, 5, 7])

# How to remove from one array those items that exist in another?
Get the positions where elements of a and b match

In [130]:
a = np.array([1,2,3,4,5,7])
b = np.array([5,6,7,8,9,3])


In [132]:
[x for x in a if x in b ]

[3, 5, 7]

In [140]:
b1 = []
for x in a:
    if x in b:
         b1.append(x)

In [141]:
b1

[3, 5, 7]

#  How to extract all numbers between a given range from a numpy array?
Get all items between 5 and 10 from a.

In [143]:
a  = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [149]:
a[(a>5) & (a<10)] 

array([6, 7, 8, 9])

# How to make a python function that handles scalars to work on numpy arrays?

Convert the function maxx that works on two scalars, to work on two arrays.

In [159]:
def max(a,b):
    if a>= b:
        return a
    else:
        return b
max(10,11)

11

In [160]:
maxx = np.vectorize(max)

In [162]:
maxx([1,2,3,45,5,43,10]
     ,[1,23,4,2,4,12,10])

array([ 1, 23,  4, 45,  5, 43, 10])