# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge.

#### Import NumPy as np

#### Create an array of 10 zeros 

__<span style="color:red">Note </span>: BE CAREFUL NOT TO RUN THE CELL WHOSE OUTPUT IS ALREADY THERE, OTHERWISE YOU WON'T BE ABLE TO SEE THE ORIGINAL ANSWER ANY MORE.__

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [4]:
## your code here
import numpy as np
var =np.zeros([10])
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [5]:
## your code here
vr =np.ones([10])
vr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [17]:
## your code here
fv = np.ones(10)*5
#fv = np.ones(10)*222220

fv

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [18]:
## your code here
vw= np.arange(10,50,1)
vw

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [33]:
## your code here
ar1 =np.arange(10,50,2)
#var1 =np.logspace(10,50,2) # linspace # logsapce
##########syntax = numpy.arange(start, stop,step) 
ar1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
# your code here
import numpy as np
x =  np.arange(2, 12).reshape(5,2)
print(x)

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
#### Create a 3x3 identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
#### your code here
id = np.identity(4)
id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

array([ 0.42829726])

In [82]:
## your code here
ba= np.random.normal(0,1,1)
ba

array([1.637945])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

In [88]:
## your code here
import random
tf = np.random.normal(0,1,25)
tf

array([-0.02328364, -1.26669456,  0.95315814, -1.59615149,  0.2235342 ,
       -0.89215809,  0.85909518,  0.23350498,  1.1296119 ,  0.5781437 ,
       -0.23874591,  1.54709878, -0.2989361 , -0.01525302, -0.32995383,
       -0.49517638,  1.76190856, -0.29484415, -0.62660146, -1.60360618,
       -1.30562094, -2.64669182, -1.44124375,  0.75085286, -1.38878647])

#### Create the following matrix:

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [3]:
import numpy as np
np.arange(1,101).reshape(10,10)/100



array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [104]:
## your code here
np.linspace(0,1,20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [0]:
## your code here

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [108]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [133]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [132]:
## your code here
mat[:2,3:]

array([[ 4,  5],
       [ 9, 10]])

In [134]:
mat[3:,:2]

array([[16, 17],
       [21, 22]])

In [137]:
mat[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [138]:
mat[2:4,1:4]

array([[12, 13, 14],
       [17, 18, 19]])

In [139]:
mat[3:,1:4]

array([[17, 18, 19],
       [22, 23, 24]])

In [140]:
mat[2:4,2:]

array([[13, 14, 15],
       [18, 19, 20]])

In [141]:
mat[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [142]:
mat[0:2,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [144]:
mat[3:,2:]

array([[18, 19, 20],
       [23, 24, 25]])

In [145]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
#np.arange(12,25,1).reshape()
mat[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [131]:
mat[:2,3:]

array([[ 4,  5],
       [ 9, 10]])

In [127]:

mat[2:,3:]
mat[3:,1:3]

array([[17, 18],
       [22, 23]])

In [0]:
## your code here

In [155]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

mat[3,3:]

array([19, 20])

20

In [154]:
## your code here
mat[3,4]


20

array([[ 2],
       [ 7],
       [12]])

In [153]:
## your code here
mat[0:3,1]

array([ 2,  7, 12])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [157]:
## your code here
mat[4,0:5]

array([21, 22, 23, 24, 25])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [158]:
## your code here
mat[3:,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

In [160]:
## your code here
mat
#sum(mat)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [168]:
mat.sum()

325

#### Get the standard deviation of the values in mat

7.2111025509279782

In [169]:
## your code here
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

In [170]:
## your code here
sum(mat)
##OR


array([55, 60, 65, 70, 75])