In [1]:
import numpy as np

In [13]:
for i in range(8):
    for l in range(i):
        print('*',end=' ')
    print('*')

*
* *
* * *
* * * *
* * * * *
* * * * * *
* * * * * * *
* * * * * * * *


In [20]:
a, b = 0, 1
amax = 100
L = []

while True:
    (a, b) = (b, a + b)
    print('hii',end = ' ')
    if a > amax:
        break
    print('v' ,L.append(a))

print(L)

hii v None
hii v None
hii v None
hii v None
hii v None
hii v None
hii v None
hii v None
hii v None
hii v None
hii v None
hii [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


# Linespace

In [21]:
np.linspace(start = 0, stop = 100, num = 5)

array([  0.,  25.,  50.,  75., 100.])

In [22]:
np.linspace(start = 0, stop = 100, num = 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [29]:
np.linspace(start = 0, stop = 100, num = 4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])